import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Where the built plugin lands. The repository root by default, which is what
 * the release workflow collects its assets from; set DNS_PLUGIN_OUTDIR, in the
 * environment or in an untracked .env, to build straight into a vault instead.
 */
function outputDirectory() {
	if (process.env.DNS_PLUGIN_OUTDIR) return process.env.DNS_PLUGIN_OUTDIR;
	if (!existsSync('.env')) return '.';
	const line = readFileSync('.env', 'utf8')
		.split('\n')
		.map((entry) => entry.trim())
		.find((entry) => entry.startsWith('DNS_PLUGIN_OUTDIR='));
	if (!line) return '.';
	return line.slice('DNS_PLUGIN_OUTDIR='.length).trim().replace(/^["']|["']$/g, '');
}

const outDir = outputDirectory();
if (outDir !== '.') mkdirSync(outDir, { recursive: true });

/** A plugin folder needs the manifest and styles beside main.js to load. */
function copyPluginAssets() {
	if (outDir === '.') return;
	for (const asset of ['manifest.json', 'styles.css']) {
		if (existsSync(asset)) copyFileSync(asset, join(outDir, asset));
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'node:*',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: join(outDir, 'main.js'),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyPluginAssets();
	process.exit(0);
} else {
	copyPluginAssets();
	await context.watch();
}
